# -*- coding: utf-8 -*-
# Deployment settings for SEofASE.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['W:/Marmalade/6.1/s3e/makefile_builder/mkb.py', 'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/SEofASE.mkb', '--deploy-only']
mkb = 'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/SEofASE.mkb'
mkf = ['w:\\marmalade\\6.1\\modules\\iw2d\\iw2d.mkf', 'w:\\marmalade\\6.1\\modules\\iwgx\\iwgx.mkf', 'w:\\marmalade\\6.1\\modules\\iwgeom\\iwgeom.mkf', 'w:\\marmalade\\6.1\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\patrick\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\patrick\\appdata\\roaming\\marmalade\\packages\\6.1.1\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\patrick\\appdata\\roaming\\marmalade\\packages\\6.1.1\\zlib_1.2.4\\zlib.mkf', 'w:\\marmalade\\6.1\\modules\\iwresmanager\\iwresmanager.mkf', 'w:\\marmalade\\6.1\\modules\\iwgl\\iwgl.mkf', 'w:\\marmalade\\6.1\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\patrick\\appdata\\roaming\\marmalade\\packages\\6.1.1\\tiniconv_1.0.1\\tiniconv.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse\data', '.', 0),
]

assets['default'] = [
]

assets['artbuild'] = [
    ('w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'SEofASE'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'SEofASE'
    long_caption = 'SEofASE'
    version = [0, 0, 1]
    config = ['w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/data/app.icf']
    data_dir = 'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Debug_SEofASE_VC10_arm/SEofASE.s3e',
                   'release' : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Release_SEofASE_VC10_arm/SEofASE.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Debug_SEofASE_VC10_gcc_mips/SEofASE.so',
                   'release' : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Release_SEofASE_VC10_gcc_mips/SEofASE.so',
                 },
         'x86' : {
                   'debug'   : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Debug_SEofASE_VC10_x86/SEofASE.s86',
                   'release' : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Release_SEofASE_VC10_x86/SEofASE.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Debug_SEofASE_VC10_gcc_arm/SEofASE.s3e',
                   'release' : r'w:/Users/Patrick/Documents/GitHub/SEttlers-of-Apocalypse/build_seofase_vc10/Release_SEofASE_VC10_gcc_arm/SEofASE.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
