# -*- coding: utf-8 -*-
# Deployment settings for SEofASE.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Developer/Marmalade/6.1/s3e/makefile_builder/mkb.py', '--buildenv=xcode', '/Users/lolium/SEttlers-of-Apocalypse/SEofASE.mkb', '--deploy-only']
mkb = '/Users/lolium/SEttlers-of-Apocalypse/SEofASE.mkb'
mkf = ['/Developer/Marmalade/6.1/modules/iw2d/iw2d.mkf', '/Developer/Marmalade/6.1/modules/iwgx/iwgx.mkf', '/Developer/Marmalade/6.1/modules/iwgeom/iwgeom.mkf', '/Developer/Marmalade/6.1/modules/iwutil/iwutil.mkf', u'/Users/lolium/.local/share/marmalade/packages/6.1.1/libjpeg_6b/libjpeg.mkf', u'/Users/lolium/.local/share/marmalade/packages/6.1.1/libpng_1.2.34/libpng.mkf', u'/Users/lolium/.local/share/marmalade/packages/6.1.1/zlib_1.2.4/zlib.mkf', '/Developer/Marmalade/6.1/modules/iwresmanager/iwresmanager.mkf', '/Developer/Marmalade/6.1/modules/iwgl/iwgl.mkf', '/Developer/Marmalade/6.1/modules/iwgxfont/iwgxfont.mkf', u'/Users/lolium/.local/share/marmalade/packages/6.1.1/tiniconv_1.0.1/tiniconv.mkf']

class DeployConfig(object):
    os = ['android']
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/lolium/SEttlers-of-Apocalypse/data', '.', 0),
]

assets['default'] = [
]

assets['artbuild'] = [
    ('/Users/lolium/SEttlers-of-Apocalypse/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    os = ['android']
    embed_icf = -1
    name = 'SEofASE'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'SEofASE'
    long_caption = 'SEofASE'
    version = [0, 0, 1]
    config = ['/Users/lolium/SEttlers-of-Apocalypse/data/app.icf']
    data_dir = '/Users/lolium/SEttlers-of-Apocalypse/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'x86' : {
                   'debug'   : r'/Users/lolium/SEttlers-of-Apocalypse/build_seofase_xcode/build/Debug/SEofASE.s86',
                   'release' : r'/Users/lolium/SEttlers-of-Apocalypse/build_seofase_xcode/build/Release/SEofASE.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/lolium/SEttlers-of-Apocalypse/build_seofase_xcode/build/Debug ARM/SEofASE.s3e',
                   'release' : r'/Users/lolium/SEttlers-of-Apocalypse/build_seofase_xcode/build/Release ARM/SEofASE.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
